name: Release

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make build

      #- uses: xu-cheng/latex-action@v2
      #  with:
      #    root_file: "src/*.tex"
      #    work_in_root_file_dir: './src'

      - uses: actions/upload-artifact@v3
        with:
          path: build/sus-fr.pdf

      - uses: actions/upload-artifact@v3
        with:
          path: build/sus-es.pdf

      - uses: actions/upload-artifact@v3
        with:
          path: build/sus-de.pdf

      - uses: actions/upload-artifact@v3
        with:
          path: build/sus-en.pdf
